import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Share Your Mind',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="x twitter social" />
        <link rel="icon" href="/x-icon.svg" />
      </head>
      <body >
          {children}
      </body>
    </html>
  )
}
